# Generated by Django 5.2.4 on 2025-07-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_city_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='District',
        ),
    ]
