# Generated by Django 4.2 on 2025-07-08 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_district_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_destinations', to='location.district'),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_origins', to='location.district'),
        ),
    ]
