# Generated by Django 4.2 on 2025-07-08 09:54

import account.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', account.managers.CustomUserManager()),
            ],
        ),
    ]
