# Generated by Django 4.2 on 2025-07-08 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parcel',
            unique_together={('sender', 'name')},
        ),
    ]
