# Generated by Django 5.2.4 on 2025-07-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_trackingstatus_delete_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingstatus',
            options={'verbose_name_plural': 'TrackingStatus'},
        ),
    ]
