# Generated by Django 5.2.4 on 2025-07-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportcompany',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
