# Generated by Django 5.2.4 on 2025-07-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_transportcompany_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportcompany',
            options={'verbose_name_plural': 'TransportCompanies'},
        ),
    ]
