# Generated by Django 4.2 on 2025-07-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_alter_route_destination_alter_route_origin'),
        ('transport', '0003_alter_transportcompany_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='routes',
            field=models.ManyToManyField(blank=True, related_name='vehicles', to='location.route'),
        ),
    ]
